# TODO: get site title, social media stuff in here and preload it before the server starts (session data? store?)
url: https://jayperryworks.com

# sitemap data for main pages (not posts)
pages:
  - data: content/home.yml
    path: ''
    priority: 1
  - data: content/about.yml
    path: about
    priority: 0.4
  - data: content/pictures.yml
    path: pictures
    priority: 0.8
    change: monthly
  - path: writing
    priority: 0.8
    change: weekly

collections:
  - name: pictures
    source: content/pictures
    sourceTemplate: :year-:slug
    pathTemplate: pictures/:year/:slug

  - name: blog
    source: content/blog
    sourceTemplate: :year-:month-:day-:slug
    pathTemplate: blog/:year/:month/:day/:slug
    redirect:
      - before: 2019
        oldPath: writing/:year/:month/:slug
      - before: 2020
        after: 2019
        oldPath: writing/:year/:month/:day/:slug

git:
  host: github
  repository: jayperryworks/jayperryworks-site
  deployBranch: cms-config