backend:
  name: github
media_folder: source/assets/uploads
public_folder: /uploads
publish_mode: editorial_workflow
collections:
  - label: Blog
    name: blog
    folder: content/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    format: yml
    editor:
      preview: false
    fields:
      - &ref_2
        label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
        required: false
      - label: Cover image
        name: cover
        widget: object
        required: false
        fields:
          - label: Image
            name: image
            widget: image
            required: false
          - label: Border
            name: border
            widget: boolean
            default: false
          - &ref_0
            label: Alt
            name: alt
            widget: string
            required: false
            hint: >-
              Add an alt attribute to describe the image for screen readers,
              etc.
          - label: Resize
            name: resize
            widget: boolean
            default: false
          - label: Caption
            name: caption
            widget: string
            required: false
          - label: Credit
            name: credit
            widget: string
            required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Body blocks
        name: body
        widget: list
        required: false
        types:
          - label: Heading
            name: heading
            widget: object
            fields:
              - label: Type
                name: type
                widget: hidden
                default: heading
              - label: Level
                name: level
                widget: number
                value_type: int
                min: 1
                max: 6
                required: false
                default: 2
              - label: Content
                name: inlineMarkdown
                widget: markdown
                required: false
          - label: Figure
            name: figure
            widget: object
            fields:
              - label: Type
                name: type
                widget: hidden
                default: figure
              - &ref_1
                label: Use in excerpt
                name: useInExcerpt
                widget: boolean
                default: false
                hint: Include this section in the post excerpt?
              - label: Prominence
                name: prominence
                widget: select
                required: false
                default: default
                hint: >-
                  Specify how wide this block should be, relative to the page
                  layout.
                options:
                  - xnarrow
                  - narrow
                  - default
                  - wide
              - label: Image
                name: image
                widget: image
              - label: Optimize the image(s)
                name: resize
                widget: boolean
                default: false
              - label: Border
                name: border
                widget: boolean
                default: false
              - *ref_0
              - label: Caption
                name: caption
                widget: markdown
                minimal: true
                required: false
              - label: Attribution
                name: attribution
                widget: string
                required: false
                hint: 'Add a photo or artist credit, if needed.'
          - label: Gallery
            name: gallery
            widget: object
            fields:
              - label: Type
                name: type
                widget: hidden
                default: gallery
              - *ref_1
              - label: Prominence
                name: prominence
                widget: select
                required: false
                default: default
                hint: >-
                  Specify how wide this block should be, relative to the page
                  layout.
                options:
                  - xnarrow
                  - narrow
                  - default
                  - wide
              - label: Size
                name: size
                widget: select
                options:
                  - small
                  - medium
                  - large
              - label: Optimize the image(s)
                name: resize
                widget: boolean
                default: false
              - label: Images
                name: images
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - *ref_0
              - label: Caption
                name: inlineMarkdown
                widget: markdown
                minimal: true
                required: false
  - label: Pictures
    name: pictures
    folder: content/pictures
    create: true
    slug: '{{year}}-{{slug}}'
    format: yml
    editor:
      preview: false
    fields:
      - *ref_2
      - label: Date
        name: date
        widget: date
        required: false
      - label: Series
        name: series
        widget: select
        options:
          - Inventory
          - Seasons
        required: false
      - label: Width
        name: width
        hint: 'Physical width, in inches'
        widget: number
        valueType: int
        required: false
      - label: Height
        name: height
        hint: 'Physical height, in inches'
        widget: number
        valueType: int
        required: false
      - label: Category
        name: category
        widget: select
        options:
          - prints
          - paintings
        default: prints
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Cover image
        name: cover
        widget: image
      - label: Thumbnail image
        name: thumb
        widget: image
      - label: Intro
        name: intro
        widget: markdown
        required: false
      - label: Editions
        name: editions
        widget: list
        required: false
        fields:
          - label: Size
            name: name
            widget: string
          - label: Type
            name: type
            widget: select
            options:
              - giclee
              - screenprint
            default: giclee
          - label: Width
            name: width
            hint: 'Physical width, in inches'
            widget: number
            valueType: int
            required: false
          - label: Height
            name: height
            hint: 'Physical height, in inches'
            widget: number
            valueType: int
            required: false
          - label: Border
            name: border
            hint: 'Physical border, in inches'
            widget: number
            valueType: int
            required: false
          - label: Price
            name: price
            widget: number
            valueType: int
          - label: Limit
            name: limit
            hint: Size of the edition; leave blank if open
            widget: number
            valueType: int
            required: false
          - label: Etsy listing
            name: url
            widget: string
          - label: Photo
            name: photo
            widget: image
